version: "2.2"

services:

    nginx: # 服务名称
        image: nginx:1.13.9-alpine # 服务使用的镜像
        container_name: nginx # 容器名称
        ports: # 服务运行端口
            - "80:80"
            - "443:443"
        environment: # 容器的环境变量
            TZ : "Asia/Shanghai" # 设置时区
#        links: # 连接其他容器的服务
#            - "php"
        volumes: # 将宿主机的文件或目录挂载到容器中
#            - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 将配置文件挂到主机
#            - ./nginx/conf.d:/etc/nginx/conf.d # 将配置文件夹挂到主机
            - ./nginx/ssl:/etc/nginx/ssl # 将证书文件夹挂在到主机
            - ./nginx/logs:/var/log/nginx # 将日志文件夹挂载到主机
            - ../wwwroot:/usr/share/nginx/html # nginx 静态资源
        restart: always # 挂断自动重新启动
        networks:
            fasti_net:
                ipv4_address: "192.63.0.11"

networks:
    fasti_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "192.63.0.0/16"
