version: "2.2"

services:

    nginx: # 服务名称
        image: nginx:1.13.9-alpine # 服务使用的镜像
        container_name: nginx # 容器名称
        ports: # 服务运行端口
            - "80:80"
            - "443:443"
        environment: # 容器的环境变量
            TZ : "Asia/Shanghai" # 设置时区
        links: # 连接其他容器的服务
            - "php"
        volumes: # 将宿主机的文件或目录挂载到容器中
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw # 将配置文件挂到主机
            - ./nginx/conf.d/:/etc/nginx/conf.d/:rw # 将配置文件夹挂到主机
            - ./nginx/ssl/:/etc/nginx/ssl/:rw # 将证书文件夹挂在到主机
            - ./nginx/logs/:/var/log/nginx/:rw # 将日志文件夹挂载到主机
            - ../wwwroot/:/usr/share/nginx/html/:rw # nginx 静态资源
        restart: always # 挂断自动重新启动
        networks:
            fasti_net:
                ipv4_address: "192.63.0.11"

    php:
        image: php:7.4-fpm-alpine # 服务使用的镜像
        container_name: php7.4-fpm # 容器名称
        ports: # 服务运行端口
            - "9000:9000"
        links: # 连接其他容器的服务
            - "mysql"
            - "redis" 
        environment: # 容器的环境变量
            TZ : "Asia/Shanghai" # 设置时区
        volumes: # 将宿主机的文件或目录挂载到容器中
            - ./php/php.ini:/usr/local/etc/php/php.ini:rw # 将配置文件挂到主机
            - ./php/conf.d:/usr/local/etc/php/conf.d/:rw # 将配置文件夹挂到主机
            - ../wwwroot/:/var/www/html/:rw # 项目目录映射
        restart: always # 挂断自动重新启动
        privileged: true # 获取特权
        networks:
            fasti_net:
                ipv4_address: "192.63.0.21"

    redis:
        image: redis:5-alpine # 服务使用的镜像
        container_name: redis # 容器名称
        mem_limit: 100m
        ports: # 服务运行端口
            - "6379:6379"
        environment: # 容器的环境变量
            TZ : "Asia/Shanghai" # 设置时区
        volumes: # 将宿主机的文件或目录挂载到容器中
            - ./redis/redis.conf:/etc/redis/redis.conf:rw # 将配置文件挂到主机
            - ./redis/data/:/data/:rw # 将数据文件夹挂载到主机
        command: redis-server /etc/redis/redis.conf # 容器执行命令
        restart: always # 挂断自动重新启动
        privileged: true # 获取特权
        networks:
            fasti_net:
                ipv4_address: "192.63.0.31"
     
    mysql:
        image: mysql:5.7 # 服务使用的镜像
        container_name: mysql # 容器名称
        ports: # 服务运行端口
            - "3306:3306"
        environment:  # 容器的环境变量
            - MYSQL_ROOT_PASSWORD = "root" # 初始化root用户的密码
            - TZ = "Asia/Shanghai" # 设置时区
        volumes: # 将宿主机的文件或目录挂载到容器中
            - ./mysql/data/:/var/lib/mysql/:rw # 将数据文件夹挂载到主机
            - ./mysql/logs/:/var/log/mysql/:rw # 将日志文件夹挂载到主机
        restart: always # 挂断自动重新启动
        privileged: true # 获取特权
        networks:
            fasti_net:
                ipv4_address: "192.63.0.41"
                
networks:
    fasti_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "192.63.0.0/16"
